M48
; DRILL file {KiCad 9.0.3} date 2025-08-18T10:51:59+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-18T10:51:59+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C5.050
%
G90
G05
T1
X38.0Y-127.0
X49.0Y-127.0
X91.0Y-127.0
X102.0Y-127.0
T2
X43.5Y-127.0
X96.5Y-127.0
M30
